### PR TITLE
ASR9K reload and login

### PR DESCRIPTION
**Pull request by joydai**
Mainly two changes:
1. For migration purpose, the reload for ASR9K classic XR and ASR9K eXR. Re-configuring authentication is implemented in CSM plugins.
2. For eXR login, return when seeing "Password OK" and only enter username once.

Tested reloads(and logins) in both ASR9K classic XR and eXR. Also the migration.

### CODE REVIEW

**Comment by kstaniek** [comment]
How does it work with SSH? Is it even possible to do the migration using SSH instead of Telnet?

**Comment by joydai** [comment]
I assumed that people would be using telnet, but I just asked Alex, we should support ssh too, so let me get ssh enabled and give it a try.

**Comment by joydai** [comment]
Actually, just tried ssh. I think it only works with mgmt IP, not console, so we will disallow migration with ssh connection. I'm going to put a restraint on that when migration jobs are scheduled.

**Comment by kstaniek** [comment]
I'm just wondering if it is possible to get the terminal server configured with ssh access to the specific port providing a direct access to the console. I guess this is a bit weird.
I think we can skip the ssh support as for now. Let me check how it works and will merge the PR.

**Pull request merged**
